deploy:
  provider: pypi
  user: mkeyno
  password:
    secure: "Your encrypted password"
    
    
# language: node_js

# node_js:
  # - "4"


# install:
  # - PATH="`npm bin`:`npm bin -g`:$PATH"
  # # Install dependencies and build
  # - npm install

# script:
  # # Output useful info for debugging
  # - node --version
  # - npm --version
  # # Run tests
  # - npm test

# branches:
  # only:
    # - master
    # - proof
    # - travis-ci

# # Not using `npm install --dev` because it is recursive. It will pull in the all
# # development dependencies for CoffeeScript. Way too much spew in the Travis CI
# # build output.

# before_install:
  # - npm install
  # - npm install istanbul coveralls

# env:
  # global:
  # - secure: "BxUHTsa1WVANLQoimilbZwa1MCWSdM9hOmPWBE/rsYb7uT/iiqkRXXwnWhKtN5CLvTvIQbiAzq4iyPID0S8UHrnxClYQrOuA6QkrtwgIEuDAmijao/bgxobPOremvkwXcpMGIwzYKyYQQtSEaEIQbqf6gSSKW9dBh/GZ/vfTsqo="
